AWSTemplateFormatVersion: "2010-09-09"
Description: Exports Amplify resource values
Parameters:
  authcognitoa7d29d9dUserPoolId:
    Type: String
    Description: Amazon Cognito User Pool ID
  apiawsserverlessairlineGraphQLAPIIdOutput:
    Type: String
    Description: AWS AppSync API ID
  apiawsserverlessairlineGraphQLAPIEndpointOutput:
    Type: String
    Description: AWS AppSync API Endpoint
  env:
    Type: String
    Description: Amplify environment
    Default: test
Resources:
  CognitoUserPoolParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub "/${env}/service/amplify/auth/userpool"
      Type: String
      Value: !Ref authcognitoa7d29d9dUserPoolId
  GraphqlApiParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub "/${env}/service/amplify/api/id"
      Type: String
      Value: !Ref apiawsserverlessairlineGraphQLAPIIdOutput
  GraphqlEndpointUrlParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub "/${env}/service/amplify/api/endpointURL"
      Type: String
      Value: !Ref apiawsserverlessairlineGraphQLAPIEndpointOutput
  FlightTableName:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub "/${env}/service/amplify/storage/flightTable"
      Type: String
      Value:
        # type Flight @model becomes a DynamoDB table exported as AppSyncApiId:GetAtt:FlightTable:Name
        Fn::ImportValue: !Sub "${apiawsserverlessairlineGraphQLAPIIdOutput}:GetAtt:FlightTable:Name"
  BookingTableName:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub "/${env}/service/amplify/storage/bookingTable"
      Type: String
      Value:
        # type Booking @model becomes a DynamoDB table exported as AppSyncApiId:GetAtt:BookingTable:Name
        Fn::ImportValue: !Sub "${apiawsserverlessairlineGraphQLAPIIdOutput}:GetAtt:BookingTable:Name"
