AWSTemplateFormatVersion: '2010-09-09'
Description: 'loyalty service

  '
Globals:
  Function:
    Timeout: 100
Outputs:
  BaseUrl:
    Description: Base URL for the API Gateway
    Value:
      Fn::GetAtt:
      - BaseUrl
      - Value
  LoyaltyDataTable:
    Description: Loyalty Data Table ARN
    Value:
      Fn::GetAtt:
      - LoyaltyDataTable
      - Arn
Parameters:
  BookingSNSTopic:
    Description: Booking SVC SNS Topic
    Type: AWS::SSM::Parameter::Value<String>
  Stage:
    Description: Stage Name
    Type: String
Resources:
  BaseUrl:
    Properties:
      Name:
        Fn::Join:
        - /
        - - /service/loyalty/api-endpoint
          - Ref: Stage
      Type: String
      Value:
        Fn::Join:
        - ''
        - - https://
          - Ref: ServerlessRestApi
          - .execute-api.
          - Ref: AWS::Region
          - .amazonaws.com/
          - Ref: ServerlessRestApiProdStage
    Type: AWS::SSM::Parameter
  GetFunc:
    Properties:
      CodeUri: s3://thulsimo-builds/baa834902ad4f68392c49ae35c986b49
      Environment:
        Variables:
          DATA_TABLE_NAME:
            Ref: LoyaltyDataTable
      Events:
        Api:
          Properties:
            Method: GET
            Path: /loyalty/{CustomerId}
          Type: Api
      Handler: get.handler
      Policies:
      - DynamoDBCrudPolicy:
          TableName:
            Ref: LoyaltyDataTable
      Runtime: nodejs8.10
    Type: AWS::Serverless::Function
  IngestFunc:
    Properties:
      CodeUri: s3://thulsimo-builds/e45810a345cf7c21c75da61027ec7dd4
      Environment:
        Variables:
          DATA_TABLE_NAME:
            Ref: LoyaltyDataTable
      Events:
        Listener:
          Properties:
            Topic:
              Ref: BookingSNSTopic
          Type: SNS
      Handler: ingest.handler
      Policies:
      - DynamoDBCrudPolicy:
          TableName:
            Ref: LoyaltyDataTable
      Runtime: nodejs8.10
    Type: AWS::Serverless::Function
  LoyaltyDataTable:
    Properties:
      AttributeDefinitions:
      - AttributeName: CustomerId
        AttributeType: S
      - AttributeName: Flag
        AttributeType: S
      - AttributeName: Id
        AttributeType: S
      BillingMode: PAY_PER_REQUEST
      GlobalSecondaryIndexes:
      - IndexName: customer-flag
        KeySchema:
        - AttributeName: CustomerId
          KeyType: HASH
        - AttributeName: Flag
          KeyType: RANGE
        Projection:
          ProjectionType: ALL
      KeySchema:
      - AttributeName: Id
        KeyType: HASH
      SSESpecification:
        SSEEnabled: true
    Type: AWS::DynamoDB::Table
Transform: AWS::Serverless-2016-10-31
