AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  loyalty service
  
Globals:
  Function:
    Timeout: 100

Parameters:
  Stage:
    Type: String
    Description: Stage Name

  BookingSNSTopic:
    Type: AWS::SSM::Parameter::Value<String>
    Description: Booking SVC SNS Topic

Resources:
  LoyaltyDataTable:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: CustomerId
          AttributeType: S
        - AttributeName: Flag
          AttributeType: S
        - AttributeName: Id
          AttributeType: S
      KeySchema:
        - AttributeName: Id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: customer-flag
          KeySchema:
            - AttributeName: CustomerId
              KeyType: HASH
            - AttributeName: Flag
              KeyType: RANGE
          Projection:
              ProjectionType: ALL
      SSESpecification:
        SSEEnabled:  yes

  IngestFunc:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: build/ingest
      Handler: index.handler
      Runtime: nodejs8.10
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref LoyaltyDataTable
      Environment:
        Variables:
          DATA_TABLE_NAME: !Ref LoyaltyDataTable
      Events:
        Listener:
          Type: SNS
          Properties:
            Topic: !Ref BookingSNSTopic

  CreateMemberFunc:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: build/create
      Handler: index.handler
      Runtime: nodejs8.10
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref LoyaltyMemberTable
      Environment:
        Variables:
          MEMBER_TABLE_NAME: !Ref LoyaltyMemberTable
      Events:
        Api:
          Type: Api
          Properties:
            Method: PUT
            Path: /loyalty

  GetFunc:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: build/get
      Handler: index.handler
      Runtime: nodejs8.10
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref LoyaltyDataTable
      Environment:
        Variables:
          DATA_TABLE_NAME: !Ref LoyaltyDataTable
      Events:
        Api:
          Type: Api
          Properties:
            Method: GET
            Path: /loyalty/{CustomerId}
  
  BaseUrl:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Join ["/", [ "/service/loyalty/api-endpoint", !Ref Stage ]]
      Type: String
      Value: !Join [ "", [ "https://", !Ref ServerlessRestApi, ".execute-api.", !Ref "AWS::Region", ".amazonaws.com/", !Ref ServerlessRestApiProdStage ]]

Outputs:
  LoyaltyDataTable:
    Value: !GetAtt LoyaltyDataTable.Arn
    Description: Loyalty Data Table ARN

  BaseUrl:
    Value: !GetAtt BaseUrl.Value
    Description: Base URL for the API Gateway