AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  loyalty service
  
Globals:
  Function:
    Timeout: 100

Parameters:
  BookingSNSTopic:
    Type: AWS::SSM::Parameter::Value<String>
    Description: Booking SVC SNS Topic

Resources:
  LoyaltyDataTable:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: customerId
          AttributeType: S
        - AttributeName: flag
          AttributeType: S
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: customer-flag
          KeySchema:
            - AttributeName: customerId
              KeyType: HASH
            - AttributeName: flag
              KeyType: RANGE
          Projection:
              ProjectionType: ALL
      SSESpecification:
        SSEEnabled:  yes

  LoyaltyMemberTable:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: CustomerId
          AttributeType: S
      KeySchema:
        - AttributeName: CustomerId
          KeyType: HASH
      SSESpecification:
        SSEEnabled:  yes

  IngestFunc:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: build/ingest/
      Handler: ingest.handler
      Runtime: nodejs8.10
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref LoyaltyDataTable
      Environment:
        Variables:
          TABLE_NAME: !Ref LoyaltyDataTable
      Events:
        Listener:
          Type: SNS
          Properties:
            Topic: !Ref BookingSNSTopic

  CreateMemberFunc:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/create
      Handler: create.handler
      Runtime: nodejs8.10
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref LoyaltyMemberTable
      Environment:
        Variables:
          MEMBER_TABLE_NAME: !Ref LoyaltyMemberTable
      Events:
        Api:
          Type: Api
          Properties:
            Method: PUT
            Path: /loyalty

  GetFunc:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: build/get/
      Handler: get.handler
      Runtime: nodejs8.10
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref LoyaltyDataTable
      Environment:
        Variables:
          TABLE_NAME: !Ref LoyaltyDataTable
      Events:
        Api:
          Type: Api
          Properties:
            Method: GET
            Path: /{customerId}

Outputs:
  LoyaltyDataTable:
    Value: !GetAtt LoyaltyDataTable.Arn
    Description: Loyalty Data Table ARN