AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  loyalty service
  
Globals:
  Function:
    Timeout: 100

Parameters:
  Stage:
    Type: String
    Description: Stage Name

  BookingSNSTopic:
    Type: AWS::SSM::Parameter::Value<String>
    Description: Booking SVC SNS Topic

Resources:
  LoyaltyDataTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub LoyaltyData-${AWS::StackName}
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: CustomerId
          AttributeType: S
        - AttributeName: Flag
          AttributeType: S
        - AttributeName: Id
          AttributeType: S
      KeySchema:
        - AttributeName: Id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: customer-flag
          KeySchema:
            - AttributeName: CustomerId
              KeyType: HASH
            - AttributeName: Flag
              KeyType: RANGE
          Projection:
              ProjectionType: ALL
      SSESpecification:
        SSEEnabled:  yes

  IngestFunc:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: build/ingest
      Handler: index.handler
      Runtime: nodejs8.10
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref LoyaltyDataTable
      Environment:
        Variables:
          TABLE_NAME: !Ref LoyaltyDataTable
      Events:
        Listener:
          Type: SNS
          Properties:
            Topic: !Ref BookingSNSTopic

  GetFunc:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: build/get
      Handler: index.handler
      Runtime: nodejs8.10
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref LoyaltyDataTable
      Environment:
        Variables:
          TABLE_NAME: !Ref LoyaltyDataTable
      Events:
        Api:
          Type: Api
          Properties:
            Method: GET
            Path: /loyalty/{customerId}
            RestApiId: !Ref LoyaltyApi
  
  LoyaltyEndpointParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub "/service/loyalty/api-endpoint/${Stage}"
      Type: String
      Value: !Sub "https://${LoyaltyApi}.execute-api.${AWS::Region}.amazonaws.com/Prod"

  LoyaltyApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: !Sub 'LoyaltyApi-${Stage}'
      StageName: Prod
      # Cors:
      #   AllowOrigin: "'*'"
      #   AllowHeaders:
      #     "'Content-Type,Authorization,X-Amz-Date'"
      #   MaxAge: "'600'"
      #TracingEnabled: True
      # AccessLogSetting:
      #   - DestinationArn: !Sub "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group/custom_log_group_name"
      #     Format: "$context.identity.sourceIp $context.identity.caller $context.identity.user [$context.requestTime] "$context.httpMethod $context.resourcePath $context.protocol" $context.status $context.responseLength $context.requestId"
      MethodSettings:
        - MetricsEnabled: True
          ResourcePath: '/*'
          HttpMethod: '*'
          ThrottlingRateLimit: 100
          ThrottlingBurstLimit: 50
      Auth:
        DefaultAuthorizer: AWS_IAM
      DefinitionBody:
        swagger: "2.0"
        x-amazon-apigateway-request-validator: all
        x-amazon-apigateway-request-validators:
          all:
            validateRequestBody: true
            validateRequestParameters: true
        produces:
          - application/json
        paths:
          "/loyalty/{customerId}":
            get:
              summary: 'Fetch customer loyalty points'
              parameters:
              - name: "customerId"
                in: "path"
                required: true
                type: "string"
              x-amazon-apigateway-integration:
                httpMethod: POST
                type: aws_proxy
                uri:
                  Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${GetFunc.Arn}/invocations

Outputs:
  LoyaltyDataTable:
    Value: !GetAtt LoyaltyDataTable.Arn
    Description: Loyalty Data Table ARN

  BaseUrl:
    Value: !Sub "https://${LoyaltyApi}.execute-api.${AWS::Region}.amazonaws.com/Prod"
    Description: Base URL for the API Gateway

  LoyaltyGetUrl:
    Value: !Sub "https://${LoyaltyApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/loyalty"
    Description: Loyalty Endpoint for retrieving loyalty points for a given customerId
