AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  loyalty service
  
Globals:
  Function:
    Timeout: 100

Parameters:
  BookingSNSTopic:
    Type: AWS::SSM::Parameter::Value<String>
    Description: Booking SVC SNS Topic

Resources:
  LoyaltyTable:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: customerId
          AttributeType: S
        - AttributeName: flag
          AttributeType: S
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: customer-flag
          KeySchema:
            - AttributeName: customerId
              KeyType: HASH
            - AttributeName: flag
              KeyType: RANGE
          Projection:
              ProjectionType: ALL
      SSESpecification:
        SSEEnabled:  yes

  IngestFunc:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: build/ingest/
      Handler: ingest.handler
      Runtime: nodejs10.x
      Environment:
        Variables:
          TABLE_NAME: !Ref LoyaltyTable
      Events:
        Listener:
          Type: SNS
          Properties:
            Topic: !Ref BookingSNSTopic

  GetFunc:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: build/get/
      Handler: get.handler
      Runtime: nodejs10.x
      Environment:
        Variables:
          TABLE_NAME: !Ref LoyaltyTable
      Events:
        Api:
          Type: Api
          Properties:
            Method: GET
            Path: /{customerId}

Outputs:
  LoyaltyTable:
    Value: !GetAtt LoyaltyTable.Arn
    Description: Loyalty Table ARN